name: Run Golf Scraper
on:
  schedule:
    - cron: '*/10 * * * *'  # Every 5 mn
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    
    - name: Cache Python packages
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    
    - name: Install Chrome for Selenium
      uses: browser-actions/setup-chrome@v1
    
    - name: Install Python packages
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install beautifulsoup4 selenium webdriver-manager
        
    - name: Create Google Sheets credentials
      run: |
        mkdir -p services
        echo '${{ secrets.GOOGLE_CREDENTIALS_JSON }}' > services/creds.json
        
    - name: Run scraper
      env:
        SENDGRID_API_KEY: ${{ secrets.SENDGRID_API_KEY }}
        FROM_EMAIL: ${{ secrets.FROM_EMAIL }}
        TO_EMAIL: ${{ secrets.TO_EMAIL }}
        GOOGLE_SHEET_ID: ${{ secrets.GOOGLE_SHEET_ID }}
      run: |
        python main.py Trigger schedule refresh
